### PR TITLE
Adding tests for the new KML validator

### PR DESCRIPTION
**Pull request by who8mycakes**
For https://github.com/mapbox/mapbox-upload-validate/issues/71, the following test cases are added to cover https://github.com/mapbox/mapbox-upload-validate/blob/master/lib/validators/kml.js:

- valid KML;
- invalid duplicate layers;
- invalid too many layers;
- general invalid

Please review @GretaCB. I think I need to add more assertions.

### CODE REVIEW

**Comment by GretaCB** [comment]
Nice push getting this out Friday. Took a peek and thinkin the following:
- When assigning a default value to a new variable, typically this value should match the `type` later assigned. For example, [these two vars](https://github.com/mapbox/mapbox-upload-validate/blob/5f9679b09a23eda549a1deb8d650a1cc03cec6df/lib/validators/kml.js#L5-L6) are assigned a default `string` value, but later assigned as a gdal object and an integer. 
- The duplicate layers test should be checking for `equal` instead of [`notEqual`](https://github.com/mapbox/mapbox-upload-validate/blob/4476e2b4124fd0ba99ef8b5b0a0899f559e78f12/test/full.validation.kml.test.js#L22). When switching, the test will fail. This points to a bug related to how duplicate layers are detected. For example, the [`layername_count` function](https://github.com/mapbox/mapbox-upload-validate/blob/5f9679b09a23eda549a1deb8d650a1cc03cec6df/lib/validators/kml.js#L8-L18) doesn't explicitly return anything, therefore [`duplicate_lyr_msg`](https://github.com/mapbox/mapbox-upload-validate/blob/5f9679b09a23eda549a1deb8d650a1cc03cec6df/lib/validators/kml.js#L37) will always be `undefined`. Looks like the `layername_count` function successfully determines duplicate layers: 

> { 'duplicate layer name': 2, 'layer 2': 2 }

but the fix is to properly pass this info to [the error handler](https://github.com/mapbox/mapbox-upload-validate/blob/5f9679b09a23eda549a1deb8d650a1cc03cec6df/lib/validators/kml.js#L38-L41). 

- One other thing to think about is whether it might be useful to pass the exact duplicate layer names within the error message to help users.

**Comment by GretaCB** [comment]
@who8mycakes how did things go with this yesterday? Any questions? Happy to run through what's happening in your `layername_cnt` function and how that relates to the duplicate error.

**Comment by who8mycakes** [comment]
@GretaCB Here's what I worked through yesterday:
 - I was returning the value from the forEach loop too early, without giving it a chance to complete. 
 - My fixture with duplicate layers had 2 instances of duplicate layers, but there was no logic to collect multiple duplicate layers and pass them to an error message.

@mapsam paired with me, and we created an empty object to pass the duplicate layer instances into, and return said object after the forEach loop. We also created a message array object to collect the names and number of repetitions of the duplicate layers so we could build an informative error message and pass this to the user. 

One simple thing that I'm still stuck on is passing the msg value to the test (https://github.com/mapbox/mapbox-upload-validate/blob/kml-disco-deux/test/full.validation.kml.test.js#L18). I'm thinking it's not in scope (https://github.com/mapbox/mapbox-upload-validate/blob/kml-disco-deux/lib/validators/kml.js#L49), but it's still coming up as `undefined` when I run my test.

**Comment by who8mycakes** [comment]
The kml-disco-deux branch tests passed in staging, sending the expected error messages to the user:

screen shot 2016-12-21 at 12 54 22 pm

cc @GretaCB @mapsam

**Pull request merged**
