### PR TITLE
[WIP] Upgrade mapnik to v2_spec

### PR DESCRIPTION
**Pull request by jakepruitt**
Upgrades node-mapnik to v2_spec. At the moment, the `test/fixtures/valid.tm2z` file is causing a parse error of `[Error: Vector Tile has LINESTRING type geometry with a CLOSE command.]`. My guess is that the fixture is using an out of date mapbox-streets (looks like v3), and updating to `mapbox-streets-v6` will help. @springmeyer spirit guidance on `.tm2z` files would be much appreciated.

Other than that, I see just one other serialtiles error.

cc/ @mapsam @springmeyer @flippmoke

### CODE REVIEW

**Comment by mapsam** [comment]
Thanks for starting to work through this @jakepruitt! Looking into the deserialization error right now. It looks like there are tests that check for poorly formatted serialites `invalid.serialtiles.gzipped.gz` that we are no longer throwing on if we encounter them since we are no longer using `vt.parse()`. I'm not exactly sure how to check this now since `vt.parse()` is deprecated.

**Comment by springmeyer** [comment]
I poked a bit at the test failures for this branch and found things quite baffling. `test/full.validation.serialtiles.test.js` is failing is ways so odd I can't quite describe it yet.

**Comment by springmeyer** [comment]
> is failing is ways so odd I can't quite describe it yet.

Ouch. Hours later.... Had duplicate mapnik versions in my tree. This caused the behavior I was seeing where I'd fix the test but then that would trigger another test to fail in the inverse way. This is because both `mapbox-upload-validate` and `tilelive` throw `DeserializationError: Invalid data` and `tilelive` was getting a different node-mapnik version.

**Comment by springmeyer** [comment]
green: https://travis-ci.org/mapbox/mapbox-upload-validate/builds/105591433

**Comment by mapsam** [comment]
Wow, thanks for poking around here @springmeyer!

> our existing test coverage appears to be completely missing for this code

Is this still something we'll want to add new tests for?

**Pull request merged**
