### PR TITLE
Validate filesize for mbtiles, serialtiles and tm2zs

### PR DESCRIPTION
**Pull request by GretaCB**
Per https://github.com/mapbox/mapbox-upload-limits/pull/5

Along for the ride:
- https://github.com/mapbox/mapbox-upload-validate/pull/54
- https://github.com/mapbox/mapbox-upload-limits/pull/7

cc @rclark @willwhite

### CODE REVIEW

**Comment by willwhite** [comment]
Hm how did the increased limit for mbtiles uploads work without this?

**Comment by GretaCB** [comment]
good point, I'm guessing they worked becasue there was no filesize limit before this?...hmmm

**Comment by rclark** [comment]
There was no mbtiles size limit -- this repo only checked on the total number of tiles.

**Comment by willwhite** [comment]
:+1:

**Pull request merged**
